export const getSidebarData = (t) => [
  {
    id: 0,
    title: t('sidebar.dashboard'),
    icon: 'dashboard-icon',
    active_icon: 'dashboard-active-icon',
    hasDropdown: false,
  },
  {
    id: 1,
    title: t('sidebar.asset'),
    icon: 'asset-icon',
    active_icon: 'asset-active-icon',
    hasDropdown: false,
  },
  {
    id: 2,
    title: t('sidebar.asset-ht-db'),
    icon: 'lane-icon',
    active_icon: 'lane-active-icon',
    hasDropdown: false,
  },
  {
    id: 3,
    title: t('sidebar.tool'),
    icon: 'tool-icon',
    active_icon: 'tool-active-icon',
    hasDropdown: false,
    },
  {
    id: 4,
    title: t('sidebar.category'),
    icon: 'category-icon',
    active_icon: 'category-active-icon',
    hasDropdown: false,
  },
  {
    id: 5,
    title: t('sidebar.lookup'),
    icon: 'lookup-icon',
    active_icon: 'lookup-active-icon',
    hasDropdown: false,
  },
  {
    id: 6,
    title: t('sidebar.report'),
    icon: 'report-icon',
    active_icon: 'report-active-icon',
    hasDropdown: false,
  },
]
